### ISSUE TITLE
Look at UBC02

### ISSUE THREAD

**Issue by majensen** [CBIIT/icdc-data-transformations#2]
make sure all is well

**Comment by ClaireWolfe** [comment]
Hey Mark, 

Ming very kindly sat down with me and checked out what I did and got everything back in sync.  I was then able to ensure I have the latest KTR files and documentation file in GitHub and created a tag for UBC02.  Disaster averted!!  

Thanks,
Claire

**Comment by majensen** [comment]
Awesome!! thanks @n2iw
